/**
 * BasicSwitch — RadioKit Example
 *
 * Demonstrates the simplest RadioKit USB Serial setup:
 *   - A rocker switch controls the built-in RGB LED (WS2812)
 *   - All widgets are declared in RADIOKIT.h (generated by the designer)
 *
 * Hardware:
 *   - lolin_s3_mini (ESP32-S3) with WS2812 RGB LED on GPIO 2
 *   - No external components needed
 *
 * Usage:
 *   1. Flash to ESP32
 *   2. Open the RadioKit app and connect via USB Serial at 1000000 baud
 *   3. Tap the switch to toggle the LED
 */

#include <Arduino.h>
#include "RADIOKIT.h"

// ── Pin definitions ───────────────────────────────────────────
#define LED_PIN      42  // Builtin LED on TrackLink V2 (L0)
#define BUTTON_PIN   14

// ────────────────────────────────────────────────────────────
void setup() {
  Serial.begin(1000000);
  delay(500);

  pinMode(LED_PIN, OUTPUT);
  digitalWrite(LED_PIN, LOW);
  pinMode(BUTTON_PIN, INPUT_PULLUP);

  led_1.rk.state = false;
  led_2.rk.state = false;

  // Initialize RadioKit from the UI config and start USB Serial.
  initRadioKit();

  RadioKit.println("--- RadioKit BasicSwitch Start ---");
  RadioKit.println("RK: Setup complete.");
}

// ── State tracking ────────────────────────────────────────────
static bool lastSwitchState = false;

// ────────────────────────────────────────────────────────────
void loop() {
  RadioKit.update();

  bool switchNow = slide_switch_1.rk.state;
  if (switchNow != lastSwitchState) {
    lastSwitchState = switchNow;
    digitalWrite(LED_PIN, switchNow ? HIGH : LOW);
  }
}

